Title: Useful links

# Useful links

* http://code.google.com/p/google-authenticator/
* http://www.openauthentication.org/about
* http://en.wikipedia.org/wiki/Google_Authenticator
* https://tools.ietf.org/html/rfc4226
* https://tools.ietf.org/html/rfc6238
* http://en.wikipedia.org/wiki/Key_%28cryptography%29
* https://github.com/dlitz/pycrypto
* https://www.dlitz.net/software/pycrypto/api/current/

